//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhpAssetComplianceWpfOneDesktop.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class FilePaths : global::System.Configuration.ApplicationSettingsBase {
        
        private static FilePaths defaultInstance = ((FilePaths)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FilePaths())));
        
        public static FilePaths Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string MineSequenceExcelFilePath {
            get {
                return ((string)(this["MineSequenceExcelFilePath"]));
            }
            set {
                this["MineSequenceExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select CSV file path")]
        public string MineSequenceCSVFilePath {
            get {
                return ((string)(this["MineSequenceCSVFilePath"]));
            }
            set {
                this["MineSequenceCSVFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string MineComplianceExcelFilePath {
            get {
                return ((string)(this["MineComplianceExcelFilePath"]));
            }
            set {
                this["MineComplianceExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string DepressurizationComplianceExcelFilePath {
            get {
                return ((string)(this["DepressurizationComplianceExcelFilePath"]));
            }
            set {
                this["DepressurizationComplianceExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select CSV file path")]
        public string DepressurizationComplianceCSVFilePath {
            get {
                return ((string)(this["DepressurizationComplianceCSVFilePath"]));
            }
            set {
                this["DepressurizationComplianceCSVFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string GeotechnicalNotesExcelFilePath {
            get {
                return ((string)(this["GeotechnicalNotesExcelFilePath"]));
            }
            set {
                this["GeotechnicalNotesExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select CSV file path")]
        public string GeotechnicalNotesCSVFilePath {
            get {
                return ((string)(this["GeotechnicalNotesCSVFilePath"]));
            }
            set {
                this["GeotechnicalNotesCSVFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string QuartersReconciliationFactorsExcelFilePath {
            get {
                return ((string)(this["QuartersReconciliationFactorsExcelFilePath"]));
            }
            set {
                this["QuartersReconciliationFactorsExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string ProcessComplianceExcelFilePath {
            get {
                return ((string)(this["ProcessComplianceExcelFilePath"]));
            }
            set {
                this["ProcessComplianceExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string ConcentrateQualityExcelFilePath {
            get {
                return ((string)(this["ConcentrateQualityExcelFilePath"]));
            }
            set {
                this["ConcentrateQualityExcelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Excel file path")]
        public string HistoricalRecordExcelFilePath {
            get {
                return ((string)(this["HistoricalRecordExcelFilePath"]));
            }
            set {
                this["HistoricalRecordExcelFilePath"] = value;
            }
        }
    }
}
