//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhpAssetComplianceWpfOneDesktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BhpAssetComplianceWpfOneDesktop.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHP AssetCompliance.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentrate Quality.
        /// </summary>
        public static string ConcentrateQuality {
            get {
                return ResourceManager.GetString("ConcentrateQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depressurization Compliance.
        /// </summary>
        public static string DepressurizationCompliance {
            get {
                return ResourceManager.GetString("DepressurizationCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geotechnical Notes.
        /// </summary>
        public static string Geotechnical {
            get {
                return ResourceManager.GetString("Geotechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Compliance.
        /// </summary>
        public static string MineCompliance {
            get {
                return ResourceManager.GetString("MineCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Sequence.
        /// </summary>
        public static string MineSequence {
            get {
                return ResourceManager.GetString("MineSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Compliance.
        /// </summary>
        public static string ProcessCompliance {
            get {
                return ResourceManager.GetString("ProcessCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarters Reconciliation Factors.
        /// </summary>
        public static string QuartersReconciliationFactors {
            get {
                return ResourceManager.GetString("QuartersReconciliationFactors", resourceCulture);
            }
        }
    }
}
