//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhpAssetComplianceWpfOneDesktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BhpAssetComplianceWpfOneDesktop.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Month Freight Template.
        /// </summary>
        public static string ActualMonthFreightTemplate {
            get {
                return ResourceManager.GetString("ActualMonthFreightTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHP AssetCompliance.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Freight Template.
        /// </summary>
        public static string BudgetFreightTemplate {
            get {
                return ResourceManager.GetString("BudgetFreightTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentrate Quality.
        /// </summary>
        public static string ConcentrateQuality {
            get {
                return ResourceManager.GetString("ConcentrateQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depressurization Compliance.
        /// </summary>
        public static string DepressurizationCompliance {
            get {
                return ResourceManager.GetString("DepressurizationCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Template.
        /// </summary>
        public static string GenerateTemplate {
            get {
                return ResourceManager.GetString("GenerateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geotechnical Notes.
        /// </summary>
        public static string Geotechnical {
            get {
                return ResourceManager.GetString("Geotechnical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Record.
        /// </summary>
        public static string HistoricalRecord {
            get {
                return ResourceManager.GetString("HistoricalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        public static string LoadImage {
            get {
                return ResourceManager.GetString("LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Record.
        /// </summary>
        public static string LoadRecord {
            get {
                return ResourceManager.GetString("LoadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Template.
        /// </summary>
        public static string LoadTemplate {
            get {
                return ResourceManager.GetString("LoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Compliance Budget Template.
        /// </summary>
        public static string Mine_ComplianceBudgetTemplate {
            get {
                return ResourceManager.GetString("Mine ComplianceBudgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Compliance.
        /// </summary>
        public static string MineCompliance {
            get {
                return ResourceManager.GetString("MineCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Compliance Budget Template.
        /// </summary>
        public static string MineComplianceBudgetTemplate {
            get {
                return ResourceManager.GetString("MineComplianceBudgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Compliance Real Template.
        /// </summary>
        public static string MineComplianceRealTemplate {
            get {
                return ResourceManager.GetString("MineComplianceRealTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Sequence.
        /// </summary>
        public static string MineSequence {
            get {
                return ResourceManager.GetString("MineSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Compliance depressurization Template.
        /// </summary>
        public static string MonthlyCompliancedepressurizationTemplate {
            get {
                return ResourceManager.GetString("MonthlyCompliancedepressurizationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Process Compliance Template.
        /// </summary>
        public static string MonthlyProcessComplianceTemplate {
            get {
                return ResourceManager.GetString("MonthlyProcessComplianceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Compliance.
        /// </summary>
        public static string ProcessCompliance {
            get {
                return ResourceManager.GetString("ProcessCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarters Reconciliation Factors.
        /// </summary>
        public static string QuartersReconciliationFactors {
            get {
                return ResourceManager.GetString("QuartersReconciliationFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Twelve Months Template.
        /// </summary>
        public static string RollingTwelveMonthsTemplate {
            get {
                return ResourceManager.GetString("RollingTwelveMonthsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Depressurization Template.
        /// </summary>
        public static string TargetDepressurizationTemplate {
            get {
                return ResourceManager.GetString("TargetDepressurizationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year and month.
        /// </summary>
        public static string YearAndMonth {
            get {
                return ResourceManager.GetString("YearAndMonth", resourceCulture);
            }
        }
    }
}
